# Generated by Django 4.2.13 on 2024-07-05 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('descripcion', models.TextField(verbose_name='Descripción del evento')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado del evento')),
            ],
            bases=('schedule.event',),
        ),
    ]
