# Generated by Django 4.2.13 on 2024-07-07 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 0, 0)),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 0, 0)),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=100),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
