# Generated by Django 4.2.13 on 2024-07-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_clubevent_end_time_alter_clubevent_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='clubevent',
            name='resultado',
        ),
    ]
