# Generated by Django 4.2 on 2024-06-28 05:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre de usuario"
                    ),
                ),
                (
                    "birth_day",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Numero telefónico"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="Correo electrónico"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario personalizado",
                "verbose_name_plural": "Usuarios personalizados",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del equipo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PiezaDePesca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especie",
                    models.CharField(blank=True, max_length=50, verbose_name="Especie"),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso"
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Longitud"
                    ),
                ),
                (
                    "metodo_de_pesca",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Método de pesca"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.customuser",
                        verbose_name="Usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="equip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users_app.equipo",
                verbose_name="Equipo",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="El grupo al que pertenece este usuario. Se le concederán los permisos correspondientes",
                related_name="customuser_set",
                to="auth.group",
                verbose_name="Permisos de usuario",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permisos específicos para este usuario",
                related_name="customer_user_permissions_set",
                to="auth.permission",
                verbose_name="Permisos de usuario",
            ),
        ),
    ]
