# Generated by Django 4.2 on 2024-06-28 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="equip",
            new_name="team",
        ),
    ]
