# Generated by Django 4.2.13 on 2024-07-20 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.TextField(max_length=100, verbose_name='Nombre del equipo')),
                ('capitan_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitan_equipo', to='users_app.customuser')),
                ('participante_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_participante_2', to='users_app.customuser')),
                ('participante_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_participante_3', to='users_app.customuser')),
                ('participante_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_participante_4', to='users_app.customuser')),
                ('participante_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_participante_5', to='users_app.customuser')),
            ],
        ),
    ]
