# Generated by Django 4.2.13 on 2024-07-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_app', '0002_alter_equipos_nombre_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='nombre_equipo',
            field=models.CharField(max_length=10, verbose_name='Nombre del equipo'),
        ),
    ]
