# Generated by Django 4.2.13 on 2024-07-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Historia del club')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=255, verbose_name='Nombre del Evento')),
                ('fecha', models.DateField(verbose_name='Fecha de participación')),
                ('resultado', models.TextField(verbose_name='Resultado')),
            ],
        ),
    ]
