# Generated by Django 4.2.13 on 2024-07-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacion',
            name='resultado',
        ),
        migrations.AddField(
            model_name='participacion',
            name='descripcion',
            field=models.CharField(default='Descripción', max_length=255),
        ),
    ]
